data:
  nside: 128
  lmax: 200
  lmin: 30
  delta_ell: 15
  nsplit: 2
  freq_strings: ['f030', 'f040', 'f090', 'f150', 'f230', 'f290']
  sensitivity_mode: "goal"
  lknee_mode: "optimistic"
  fsky: 0.1
  cov_scalar_ell: "camb_lens_nobb.dat"
  cov_tensor_ell: "camb_lens_r1.dat"
  highpass_delta_ell: 5

fixed_params:
  freq_pivot_dust: 353.0e+9
  temp_dust: 19.6

params:
  r_tensor:
    prior_type: "HalfNormal"
    prior_params: [0.15]
    true_value: 0.01
  A_lens:
    prior_type: "TruncatedNormal"
    prior_params: [0.4, 0.3, 0, 10]
    true_value: 0.45
  A_d_BB:
    prior_type: "TruncatedNormal"
    prior_params: [5, 2, 0, 20]
    true_value: 4
  alpha_d_BB:
    prior_type: "Normal"
    prior_params: [-0.2, 1.0]
    true_value: -0.3
  beta_dust:
    prior_type: "Normal"
    prior_params: [1.59, 0.11]
    true_value: 1.55
  amp_beta_dust:
    prior_type: "TruncatedNormal"
    prior_params: [0.3, 0.5, 0, 1.59]
    true_value: 0.4
  gamma_beta_dust:
    prior_type: "TruncatedNormal"
    prior_params: [-4., 1., -6., -1.5]
    true_value: -3.5
  
