data:
  nside: 128
  lmax: 120
  lmin: 30
  delta_ell: 25
  nsplit: 2
  freq_strings: ['f030', 'f040', 'f090', 'f150', 'f230', 'f290']
  sensitivity_mode: "goal"
  lknee_mode: "optimistic"
  fsky: 0.1
  cov_scalar_ell: "camb_lens_nobb.dat"
  cov_tensor_ell: "camb_lens_r1.dat"

fixed_params:
  freq_pivot_dust: 353
  temp_dust: 19.6

params:
  r_tensor:
    prior_type: "HalfNormal"
    prior_params: [0.1]
    true_value: 0.01
  A_lens:
    prior_type: "Normal"
    prior_params: [1, 0.3]
    true_value: 1
  A_d_BB:
    prior_type: "Normal"
    prior_params: [5, 2]
    true_value: 5
  alpha_d_BB:
    prior_type: "Normal"
    prior_params: [-0.2, 0.5]
    true_value: -0.2
  beta_dust:
    prior_type: "Normal"
    prior_params: [1.59, 0.11]
    true_value: 1.59
  